### ISSUE TITLE
yo angular:app is blocking the whole IDE.

### ISSUE THREAD

**Issue by Chris2011** [GeertjanWielenga/YoNetBeans#2]
I tried the generator-angular with yo angular:app and I think, atm you will add YES as the default behaviour for choices right? If it is so, there is a problem with this as you can see it in my screenshot. It's waiting for the next choice.
![yeomanisblocking](https://cloud.githubusercontent.com/assets/795658/6348681/69199870-bc22-11e4-9b8e-4fd6778e3b41.png)

Regards

Chris

**Comment by GeertjanWielenga** [comment]
Yes, these are problems with the plugin, which is why I put it on hold for the moment. If you can figure these things out, would be great.
Gj 

```
 On Tuesday, February 24, 2015 12:41 PM, Chris2011 <notifications@github.com> wrote:
```

 I tried the generator-angular with yo angular:app and I think, atm you will add YES as the default behaviour for choices right? If it is so, there is a problem with this as you can see it in my screenshot. It's waiting for the next choice.
RegardsChris—

**Comment by Chris2011** [comment]
I had a look at WebStorm 11. They added yeoman to the IDE and I think they will read out the options, show radio buttons/checkboxes and so on to add your choice. Here you can see a little screencapture. 
![yeomanwebstorm](https://cloud.githubusercontent.com/assets/795658/11398374/6e38c782-9380-11e5-9892-dfc8f44a58d7.gif)

**Comment by Chris2011** [comment]
This is what I found from my research how WebStorm did this. Hope it helps a bit more. Atm I don't know how to implement it by my own. Maybe you can start with a sample and I can contribute.

**Comment by Chris2011** [comment]
As someone in this ticket figured out: https://netbeans.org/bugzilla/show_bug.cgi?id=244441
that there is already such API to implement Yeoman into editors/IDE's: http://yeoman.io/authoring/integrating-yeoman.html

This will bring us forward. Maybe if I have time, I will have a look.

**Comment by Chris2011** [comment]
I started to implement logic to read your installed global generators: https://github.com/Chris2011/NbYeoman and it looks similar to the implementation of WebStorm. Only FYI. The big feature is missing to implement the logic to interact with the cmdline like in webstorm.

**Comment by GeertjanWielenga** [comment]
Nice. Blog about it, share the knowledge, doesn't have to be perfect.

**Comment by GeertjanWielenga** [comment]
The Yeoman API is only in JavaScript, i.e., this is the link you provided. That's not a Java API for implementing Yeoman kinto IDEs -- it is a JavaScript API: http://yeoman.io/authoring/integrating-yeoman.html Is WebStorm using that same API?

**Comment by GeertjanWielenga** [comment]
Yes, your logic to read installed global generators is the same as mine, not sure why a separate GitHub project is needed for that.

**Comment by Chris2011** [comment]
Yes the API is a javascript API, but I think java can call this things too? I asked intelliJ whether they used the same API for the implementation but didn't get an answer yet. I think you need a wrapper in java for this api.

My intentions for the repo was only for the styling. First I wanted to implemented the API stuff by my own but I started with the styling, it isn't so overloaded and it looks much more clearer. After this I canceled early the work. So again it was only to create a cleaner UI for the global generators as I saw it in WebStorm, thats all.

**Comment by Chris2011** [comment]
For me it was only a uX decision. You don't need to see all commands/generators from the beginning. You should only see the installed generators. If you want to install a new one, you have a button with a label: "Install generator" which opens a new window or whatever, where you can search for a generator and install it. So at the beginning you don't need to see 2 lists of everything.

**Comment by GeertjanWielenga** [comment]
That Java wrapper would be Nashorn. One would use Nashorn to call those JavaScript APIs. But I very much doubt WebStorm does that and I'm not going to do it like that either. About the UX design, yes, I;'m moving the ability to install new generators to the Options window, I agree you don't need those right at the beginning of the wizard.

**Comment by Chris2011** [comment]
Ok I will do more research and will talk to the WebStorm guys If I get one. Maybe they can tell me what they did.

**Comment by anstarovoyt** [comment]
Hi. I am a developer of the WebStorm-Yeoman integration. The API http://yeoman.io/authoring/integrating-yeoman.html  is used:  we start a separate yeoman-wrapper node.js  process and communicate with the process using simple stdin/stdout.

**Comment by Chris2011** [comment]
@anstarovoyt thx for the info, will help a lot :)

**Comment by Chris2011** [comment]
Hey @anstarovoyt can you give more info for this, if possible? Do you created a java command line wrapper for this or a swing component?

**Comment by Chris2011** [comment]
Maybe it will be easier (for me) to handle this with a DukeScript UI, so I can talk to the Java backend which will handle the connection between the input, coming from the UI and the output, coming from yo.

**Comment by Chris2011** [comment]
I forked the repo and I'm looking into this anyway. Thx for all the info.
